# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - visualiz-cms1

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: pull repository
        run: |
          git clone https://github.com/rempei-okada/maccha.git
          cd ./maccha/maccha.client
          yarn install
          yarn run build
          cp -rf ./public ../../
          cd ../maccha.server
          yarn install
          yarn run build
          rm -rf ./node_modules
          cd ../../
          yarn install
          rm -rf ./maccha
          mkdir app
          zip -qq -r ./app/pack.zip ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: unzip packages
        run: |
          unzip -qq ./app/pack.zip -d .

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "visualiz-cms1"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_89C82721EC054FD7AE0799DD9C6A9EEB }}
          package: .
